---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.docker
    version: 4.8.2
  - name: forgejo.forgejo
    version: 1.0.0

roles:
  - name: geerlingguy.docker
    version: 7.8.0
  - name: paperless_ngx.paperless_ngx
    version: 4.1.0
