---
- name: Install docker on all servers
  hosts: prod
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install docker
      ansible.builtin.include_role:
        name: geerlingguy.docker

- name: Install Traefik.
  hosts: traefik
  tasks:
    - name: Create Traefik directory.
      ansible.builtin.file:
        path: "{{ traefik_dir }}"
        state: directory
        mode: '0770'

    - name: Create Traefik env file from template.
      ansible.builtin.template:
        src: templates/traefik/traefik.env.j2
        dest: "{{ traefik_dir }}/traefik.env"
        mode: '0644'

    - name: Copy Traefik static config.
      ansible.builtin.copy:
        src: files/traefik/traefik.yaml
        dest: "{{ traefik_dir }}/traefik.yaml"
        mode: '0644'

    - name: Copy Traefik dynamic config.
      ansible.builtin.copy:
        src: files/traefik/dynamic/
        dest: "{{ traefik_dir }}/dynamic/"
        mode: '0770'

    - name: Install Traefik.
      ansible.builtin.include_role:
        name: traefik


- name: Install Pocket ID.
  hosts: pocket-id
  tasks:
    - name: Create Pocket-Id root and data directory.
      ansible.builtin.file:
        path: "{{ pocket_id_data_dir }}"
        state: directory
        mode: '0770'

    - name: Copy docker-compose file.
      ansible.builtin.copy:
        src: files/pocket-id/docker-compose.yml
        dest: "{{ pocket_id_dir }}/docker-compose.yml"
        mode: '0770'

    - name: Template .env file.
      ansible.builtin.template:
        src: templates/pocket-id/.env.j2
        dest: "{{ pocket_id_dir }}/.env"
        mode: '0660'

    - name: Start with docker-compose.
      community.docker.docker_compose_v2:
        project_src: "{{ pocket_id_dir }}"
        state: present

- name: Install caddy
  hosts: caddy
  tasks:
   # See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes
    - name: Set read buffer size to 7.5 MB
      ansible.posix.sysctl:
        name: net.core.rmem_max
        value: 7500000
        state: present
      ignore_errors: true
      register: caddy_ignore_errors_register_rmem

    - name: Set write buffer size to 7.5 MB
      ansible.posix.sysctl:
        name: net.core.wmem_max
        value: 7500000
        state: present
      ignore_errors: true
      register: caddy_ignore_errors_register_wmem

    - name: Copy Caddyfile
      ansible.builtin.copy:
        src: files/roles/caddy/Caddyfile
        dest: "{{ caddy_dir }}/Caddyfile"
        mode: '0770'

    - name: Install caddy-cloudflare
      ansible.builtin.include_role:
        name: caddy

- name: Install immich
  hosts: immich
  tasks:
      # See https://github.com/jemalloc/jemalloc/issues/1328
    - name: Enable memory overcommit workaround for immich_redis
      ansible.posix.sysctl:
        name: vm.overcommit_memory
        value: 1
      become: true

    - name: Install immich
      ansible.builtin.include_role:
        name: immich

- name: Install mealie
  hosts: mealie
  tasks:
    - name: Create mealie directory.
      ansible.builtin.file:
        path: "{{ mealie_dir }}"
        state: directory
        mode: "0660"

    - name: Copy docker-compose file.
      ansible.builtin.copy:
        src: files/mealie/docker-compose.yml
        dest: "{{ mealie_dir }}/docker-compose.yml"
        mode: "0660"

    - name: Template .env file.
      ansible.builtin.template:
        src: templates/mealie/.env.j2
        dest: "{{ mealie_dir }}/.env"
        mode: "0660"

    - name: Deploy Mealie with docker-compose.
      community.docker.docker_compose_v2:
        project_src: "{{ mealie_dir }}"
        state: present

- name: Install nextcloud
  hosts: nextcloud
  tasks:
    - name: Install nextcloud
      ansible.builtin.include_role:
        name: nextcloud

- name: Install paperless
  hosts: paperless
  tasks:
    - name: Create paperless directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ paperless_dir }}/data"
        - "{{ paperless_media_dir }}"
        - "{{ paperless_dir }}/export"
        - "{{ paperless_dir }}/consume"

    - name: Copy docker-compose file.
      ansible.builtin.copy:
        src: files/paperless/docker-compose.yaml
        dest: "{{ paperless_dir }}/docker-compose.yml"
        mode: "0660"

    - name: Template .env file.
      ansible.builtin.template:
        src: templates/paperless/.env.j2
        dest: "{{ paperless_dir }}/.env"
        mode: "0660"

    - name: Deploy Paperless-ngx with docker-compose.
      community.docker.docker_compose_v2:
        project_src: "{{ paperless_dir }}"
        state: present
