---
prod:
  children:
    lxc:
      hosts:
        actual:
          ansible_host: actual.lan
        grafana:
          ansible_host: grafana.lan
        influxdb:
          ansible_host: influxdb.lan
        mealie:
          ansible_host: mealie.lan
        opencloud:
          ansible_host: opencloud.lan
        paperless:
          ansible_host: paperless.lan
        pocket-id:
          ansible_host: pocket-id.lan
        traefik:
          ansible_host: traefik.lan
    vms:
      hosts:
        immich:
          ansible_host: 10.42.20.194
        microfridge:
          ansible_host: microfridge
          ansible_user: aniseed
          ansible_ssh_private_key_file: /root/.ssh/aniseed
