---
prod:
  children:
    lxc:
      hosts:
        actual:
          ansible_host: actual.lan
        grafana:
          ansible_host: grafana.lan
        influxdb:
          ansible_host: influxdb.lan
        mealie:
          ansible_host: mealie.lan
        opencloud:
          ansible_host: opencloud.lan
        paperless:
          ansible_host: paperless.lan
        pocket-id:
          ansible_host: pocket-id.lan
        traefik:
          ansible_host: traefik.lan
    vms:
      hosts:
        immich:
          ansible_host: 10.42.20.194
k8s_prod:
  children:
    server:
      hosts:
        10.42.20.10:
    agent:
      hosts:
        10.42.20.15:
        10.42.20.30:
        10.42.20.31:
    hardware:
      hosts:
        10.42.20.10:
        10.42.20.15:
